### ISSUE TITLE
Luminaire is just not turning off

### ISSUE THREAD

**Issue by alxgross** [hellqvio86/casambi#4]
Snälla Olof,

please help me. I am using your test code but equally to my own implementation via websockets the luminaire ist just not turned off, when told to turn off. unit id is right, but nothing happens. What can be the issue? Do you have any ideas? When using the web console on developer.casambi.com it works like a charm.

Kindly yours, Alexander

**Comment by hellqvio86** [comment]
Hi,
This library is not handling the websockets, it just sends commands to the api, its not reading the response. I would advice you to look at https://github.com/hellqvio86/home_assistant_casambi and the underlying library https://github.com/hellqvio86/aiocasambi . That library is handling some of the responses. 

Most of the problems I have is because of the gateway (android app is crashing a lot), one of the thing I would look at is the json message, tying is important. 

But I don't have that much to go to, you have to provide logs (please remove secrets).

Best Regards Olof Hellqvist

**Comment by alxgross** [comment]
Hej Olof,

thank you for the clarification. I'm aware. Currently, it is more an intellectual project of mine. In the meantime, I believe the error is somewhere in the websockets library. I adjusted my program to use websocket-client instead and then it worked. With websockets lib I never got the necessary "openWireSucceed"; funny enough the usual follow up "peerChanged" message came through... 

Well, I'll look into using your aiocasambi-lib instead of implementing myself. 

Ha det bra, 
ALX

**Comment by hellqvio86** [comment]
Ok, you might not be listening long enough on the websocket, thats my guess. Or you have found a bug on the Casambi side, that might be a possibility.

aiocasambi is my first attempt of writing a asyncio library, so its a bit of a mess. Its used by the casambi integration for Home assistant (which was my end goal), might be easiest to se how I use the library in that project.

Its not that hard to write a listener for the websocket (server) if you don't prefer asyncio library, but that needs to be done in order to do proper debugging of the issue.
